import "./globals.css";
import "./variables.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import { IsMenuOpenContextProvider } from "@/context/IsMenuOpenContext";
import { Playfair_Display } from "next/font/google";

export const Playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <IsMenuOpenContextProvider>
      <html lang="en">
        <body className={`${inter.className} ${Playfair.className}`}>
          <Navbar />
          {children}
        </body>
      </html>
    </IsMenuOpenContextProvider>
  );
}
